Help("""
Invocation:

    Make:
    $ python3 scons-local-3.1.1/scons.py

    Clean:
    $ python3 scons.py -c

    Quiet:
    $ scons -Q

""")

import os

link_libs = 'LabJackM'
ccflags = '-g -Wall'
env = Environment(CCFLAGS = ccflags)

examples_src = Split("""
    device_info.c
    error.c
    names_to_addresses.c
    raw_bytes.c
    read_cal.c
    read_ljm_config.c
    set_timeout.cpp
    stepwise_feedback.c
    stream_log_testing.c
    t7_tcp_configure.c
    thermocouple_example.c
""")

# Make
for example in examples_src:
    lib = env.Program(target = os.path.splitext(example)[0], source = example, LIBS = link_libs)


