Help("""
Invocation:

    Make:
    $ python3 scons-local-3.1.1/scons.py

    Clean:
    $ python3 scons.py -c

    Quiet:
    $ scons -Q

""")

import os

link_libs = 'LabJackM'
ccflags = '-g -Wall'
env = Environment(CCFLAGS = ccflags)

examples_src = Split("""
    list_all.c
    list_all_extended.c
""")

# Make
for example in examples_src:
    lib = env.Program(target = os.path.splitext(example)[0], source = example, LIBS = link_libs)


